import type { Metadata } from 'next'
import Link from 'next/link'
import { ResponsiveImage } from '@/components/ResponsiveImage'

export const metadata: Metadata = { title: 'Usluge', description: 'RIMAM pruža usluge povezane s prodajom, kupnjom i najmom nekretnina u Zagrebu i Hrvatskoj.', alternates: { canonical: '/usluge/' } }

const services = [
  { id: 'prodaja', title: 'Prodaja nekretnine', image: 'zagreb-fasada', alt: 'Ilustrativna fotografija gradske arhitekture', text: 'Kupac najprije vidi fotografije, cijenu i osnovne podatke. Jasna prezentacija pomaže mu razumjeti prostor prije prvog obilaska. Recite nam što prodajete i što biste željeli istaknuti.' },
  { id: 'kupnja', title: 'Kupnja nekretnine', image: 'interijer-detalj', alt: 'Svijetao interijer s pogledom na grad, konceptualna fotografija', text: 'Dobra potraga počinje kriterijima: lokacija, raspored, veličina i okvirna cijena. Kada znamo što vam je važno, lakše je razlikovati zanimljiv oglas od prostora koji vrijedi pogledati uživo.' },
  { id: 'najam', title: 'Najam i iznajmljivanje', image: 'mediteransko-dvoriste', alt: 'Kameno dvorište s maslinom, konceptualna fotografija', text: 'Kod najma su jednako važni prostor i uvjeti. Javite nam tražite li nekretninu ili je želite ponuditi, uz osnovne podatke o lokaciji, veličini i trajanju najma.' },
]

export default function Usluge() { return <main id="sadrzaj" className="services-page"><div className="container page-intro"><p className="eyebrow">Usluge</p><h1>Pravi prostor.<br /><em>Jasan put do njega.</em></h1><p>Prodaja, kupnja ili najam počinju istim pitanjem: što vam je doista važno? U nastavku odaberite temu o kojoj želite razgovarati.</p></div><section className="services-editorial container" aria-label="Usluge RIMAM">{services.map((service, i) => <article id={service.id} className="service-feature" key={service.title} data-reveal><div className="service-feature-photo"><ResponsiveImage src={`/optimized/images/${service.image}.webp-1600.webp`} alt={service.alt} width={1600} height={1000} loading={i === 0 ? 'eager' : 'lazy'} sizes="(max-width: 760px) 100vw, 46vw" /></div><div className="service-feature-copy"><span className="service-feature-number">0{i + 1}</span><h2>{service.title}</h2><p>{service.text}</p><Link href="/kontakt/" className="text-link">Pošaljite upit <span>↗</span></Link></div></article>)}</section><section className="service-cta container" data-reveal><div><p className="eyebrow">Razgovarajmo</p><h2>Svaka nekretnina ima svoju priču. Recite nam svoju.</h2></div><Link className="button button-dark" href="/kontakt/">Kontaktirajte nas <span>↗</span></Link></section></main> }
